
- name: Upadte and Upgrade OS
  import_tasks: update.yml
- name: Upadte and Upgrade OS
  import_tasks: upgrade.yml

- name: Ensure {{ documents_root }} directory has correct permissions.
  file:
    path: "{{ documents_root }}"
    state: directory
    owner: root
    group: www-data
    mode: u=rw,g=rX,o=r
  tags: ['permission']

- name: Ensure {{ documents_root }}/{{ current_root }} directory has correct permissions.
  file:
    path: "{{ documents_root }}/{{ current_root }}"
    state: directory
    owner: root
    group: www-data
    mode: u=rw,g=rX,o=r
  tags: ['permission']

- name: add github ssh key
  copy: >
    src=files/{{current_root}}.key
    dest={{key_path}}/{{current_root}}.key
    owner=root
    group=root
    mode=0600

- name: store the statistics of {{ documents_root }}/{{ current_root }} in the 'destFolder' variable
  stat:
    path: "{{ documents_root }}/{{ current_root }}"
  register: destFolder

- name: Reset any changes other then GIT
  command: git reset --hard
  args:
    chdir: "{{ documents_root }}/{{ current_root }}"
  when: destFolder.stat.nlink >= 3

- name: Checkout Code from Git Repository
  ansible.builtin.git: >
    repo={{ current_repo }}
    dest={{ documents_root }}/{{ current_root }}
    key_file={{key_path}}/{{current_root}}.key
    accept_hostkey=yes
    update=yes
    clone=yes

- name: Set User permission.
  file: dest={{ documents_root }}/{{ current_root }}/{{ item }} owner=sammy group=www-data mode=u=rwX,g=rX,o=rX recurse=yes
  loop: ['/']

- name: Set Project Directory permission.
  file: dest={{ documents_root }}/{{ current_root }}/{{ item }} owner=www-data group=www-data mode=u=rwX,g=rX,o=rX recurse=yes
  loop: ['storage','public/images','public/document']

- name: Add Env File
  copy: >
    src=files/.env
    dest={{ documents_root }}/{{ current_root }}/.env
    owner=sammy
    group=www-data
    mode=0644

- name: "Composer install"
  composer:
    command: install
    global_command: false
    working_dir: "{{ documents_root }}/{{ current_root }}"
  become: yes
  become_user: sammy

- name: Run artisan clear-compiled
  shell: php {{ documents_root }}/{{ current_root }}/artisan clear-compiled
  become: yes
  become_user: sammy

- name: "Composer dump-autoload"
  composer:
    command: dump-autoload
    global_command: false
    working_dir: "{{ documents_root }}/{{ current_root }}"
  become: yes
  become_user: sammy

- name: Run artisan clear-compiled
  shell: php {{ documents_root }}/{{ current_root }}/artisan optimize
  become: yes
  become_user: sammy

- name: Ensure {{ documents_root }}/{{ current_root }} directory has correct permissions.
  file:
    path: "{{ documents_root }}/{{ current_root }}"
    state: directory
    owner: sammy
    group: www-data
    mode: u=rw,g=r,o=r
  tags: ['permission']

- name: Set {{ documents_root }}/{{ current_root }}/* files permission.
  file:
    path: "{{ documents_root }}/{{ current_root }}"
    owner: sammy
    group: www-data
    mode: u=rw,g=r,o=r
    recurse: yes
  tags: ['permission']

- name: Set {{ documents_root }}/{{ current_root }}/* directories permission.
  file:
    path: "{{ documents_root }}/{{ current_root }}"
    state: directory
    owner: sammy
    group: www-data
    mode: u=rw,g=rX,o=r
    recurse: yes
  tags: ['permission']

- name: Set Project Directory permission.
  file:
    path: "{{ documents_root }}/{{ current_root }}/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwX,g=rX,o=r
    recurse: yes
  loop: ['storage']
  tags: ['permission']

- name: Set Project Directory permission.
  file:
    path: "{{ documents_root }}/{{ current_root }}/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: u=rw,g=r,o=r
    recurse: yes
  loop: ['public/images','public/document']
  tags: ['permission']